# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: LaNotte24Ore CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      DATABASE_KEY: ${{ secrets.DATABASE_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - name: Install Python and Node dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        npm install --save
    - name: Compile CSS
      run: |
        npm run dev
    - name: Endpoints test
      run: |
        python -m pytest -v